config/routes.rb
SecondScreen::Application.routes.draw do
  resources :statuses

  resources :users

  resources :broadcasts do
    collection do
      get 'now'
    end
    resources :statuses
  end

  resources :channels do
    member do
      post 'ingest'
    end
  end

  resources :broadcasters do
    resources :channels
  end
  
  resources :channels do
    resources :broadcasts
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base  
  attr_accessible :ingestion_module, :ingestion_url, :logo_url, :name, :logo
  has_attached_file :logo, :styles => {:medium => "50x50>", :large => "100x100>", :hd => "80x80>", :xhd => "120x120>"} 
  
  belongs_to :broadcaster
  
  def ingest(date)
    logger.debug ingestion_module + ".perform_async(#{id}, '#{date}')"
    eval(ingestion_module + ".perform_async(#{id}, '#{date}')")
  end
  
  def as_json(options={})
    { :id => id,
      :broadcaster_id => broadcaster_id, 
      :logoUrl => IMAGE_HOST + logo.url(:large),
      :name => name }
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  # GET /channels
  # GET /channels.json
  def index
    if params[:broadcaster_id]
      @channels = Channel.where(:broadcaster_id => params[:broadcaster_id])
    else
      @channels = Channel.all
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @broadcaster = Broadcaster.find(params[:broadcaster_id])
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @broadcaster = Broadcaster.find(params[:broadcaster_id])
    @channel = Channel.new(params[:channel])
    @channel.broadcaster_id = @broadcaster.id

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = Channel.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end
  
  def ingest
    @channel = Channel.find(params[:id])
    @channel.ingest(params[:date])
    
    respond_to do |format|
      format.html { redirect_to channel_url(@channel) }
      format.json { render json: @channel }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for([@broadcaster, @channel], :html => {:multipart => true}) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :ingestion_url %><br />
    <%= f.text_field :ingestion_url %>
  </div>
  <div class="field">
    <%= f.label :ingestion_module %><br />
    <%= f.text_field :ingestion_module %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Logo</th>
    <th>Ingestion url</th>
    <th>Ingestion module</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @channels.each do |channel| %>
  <tr>
    <td><%= channel.name %></td>
    <td><%= image_tag channel.logo.url(:large) %></td>
    <td><%= channel.ingestion_url %></td>
    <td><%= channel.ingestion_module %></td>
		<td> <%= form_tag(:controller => :channels, :id => channel.id, :action => :ingest, :method => :post) do |f| %>
		  	<div class="field">
		    	<%= label_tag :date %>
		    	<%= text_field_tag :date %>
			</div>
			<div class="actions">
				<%= submit_tag %>
			</div>
		<% end %>
	</td>
	<td><%= link_to 'Broadcasts', channel_broadcasts_path(channel)%></td>
    <td><%= link_to 'Show', channel %></td>
    <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
    <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Channel', new_channel_path %> <%= link_to 'Broadcasters', broadcasters_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @channel.name %>
</p>

<p>
  <b>Logo</b>
  <%= @channel.logo.url(:medium) %>
</p>

<p>
  <b>Ingestion url:</b>
  <%= @channel.ingestion_url %>
</p>

<p>
  <b>Ingestion module:</b>
  <%= @channel.ingestion_module %>
</p>


<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>