config/routes.rb
SecondScreen::Application.routes.draw do
  resources :statuses

  resources :users

  resources :broadcasts do
    collection do
      get 'now'
    end
    resources :statuses
  end

  resources :channels do
    member do
      post 'ingest'
    end
  end

  resources :broadcasters do
    resources :channels
  end
  
  resources :channels do
    resources :broadcasts
  end

end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base
  attr_accessible :broadcaster_broadcast_id, :broadcaster_program_id, 
                  :channel_id, :end, :start, :subtitle, :synopsis, :title, :uuid,
                  :broadcast_list
                  
  attr_reader :SECONDS_BEFORE_FILTER, :SECONDS_AFTER_FILTER
  
  acts_as_taggable
  acts_as_taggable_on :broadcasts
  
  SECONDS_BEFORE_FILTER = 60*60*12
  SECONDS_AFTER_FILTER = 60*60*12
  
  ##
  # each broadcast needs a uuid for referencing
  
  after_initialize do
    self.uuid ||= SecureRandom.uuid
  end
  
  ##
  # fetch all the shows which are running today.
  # today is defined by before and after filters
  
  def self.today(channel_id=nil)
    if channel_id
    self.where(:channel_id => channel_id).
            where("start >= ? and end <= ?", 
                  Time.now - SECONDS_BEFORE_FILTER, 
                  Time.now + SECONDS_AFTER_FILTER)
    else
      self.where("start >= ? and end <= ?", 
                  Time.now - SECONDS_BEFORE_FILTER, 
                  Time.now + SECONDS_AFTER_FILTER)   
    end
  end
  
  ##
  # fetch a list of shows across all channels which are on now
  
  def self.now
    self.where("start <= ? and end >= ?", Time.now, Time.now )
  end
  
  ##
  # search_terms gathers all the search terms that can be used for
  # a show, and returns them as a search string which can be used
  # as part of a twitter search, or any other search
  
  def search_terms
    return self.broadcast_list
  end
  
  ##
  # @param terms = {:series=>"", :episode=>"", :broadcast=>""}
  def search_terms=(terms)
    self.broadcast_list = terms[:broadcast]
    self.save
  end
  
  def as_json(options={})
    { :channel_id => channel_id,
      :start => start,
      :end => self.end,
      :title => title,
      :subtitle => subtitle,
      :synopsis => synopsis,
      :uuid => uuid}
  end

end

app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  # GET /broadcasts
  # GET /broadcasts.json
  def index
    @broadcasts = Broadcast.today(params[:channel_id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @broadcasts }
    end
  end

  # GET /broadcasts/1
  # GET /broadcasts/1.json
  def show
    @broadcast = Broadcast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @broadcast }
    end
  end

  # GET /broadcasts/new
  # GET /broadcasts/new.json
  def new
    @broadcast = Broadcast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @broadcast }
    end
  end

  # GET /broadcasts/1/edit
  def edit
    @broadcast = Broadcast.find(params[:id])
  end

  # POST /broadcasts
  # POST /broadcasts.json
  def create
    @broadcast = Broadcast.new(params[:broadcast])

    respond_to do |format|
      if @broadcast.save
        format.html { redirect_to @broadcast, notice: 'Broadcast was successfully created.' }
        format.json { render json: @broadcast, status: :created, location: @broadcast }
      else
        format.html { render action: "new" }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /broadcasts/1
  # PUT /broadcasts/1.json
  def update
    @broadcast = Broadcast.find(params[:id])

    respond_to do |format|
      if @broadcast.update_attributes(params[:broadcast])
        format.html { redirect_to @broadcast, notice: 'Broadcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /broadcasts/1
  # DELETE /broadcasts/1.json
  def destroy
    @broadcast = Broadcast.find(params[:id])
    @broadcast.destroy

    respond_to do |format|
      format.html { redirect_to broadcasts_url }
      format.json { head :no_content }
    end
  end
  
  def now
    @broadcasts = Broadcast.now
    
    respond_to do |format|
      format.html
      format.json { render json: @broadcasts}
    end
  end

end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/views/broadcasts/_form.html.erb
<%= form_for(@broadcast) do |f| %>
  <% if @broadcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@broadcast.errors.count, "error") %> prohibited this broadcast from being saved:</h2>

      <ul>
      <% @broadcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :channel_id %><br />
    <%= f.number_field :channel_id %>
  </div>
  <div class="field">
    <%= f.label :broadcaster_broadcast_id %><br />
    <%= f.text_field :broadcaster_broadcast_id %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :broadcaster_program_id %><br />
    <%= f.text_field :broadcaster_program_id %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br />
    <%= f.text_area :synopsis %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
    <div class="field">
    <%= f.label :broadcast_list %><br />
    <%= f.text_field :broadcast_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/broadcasts/edit.html.erb
<h1>Editing broadcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @broadcast %> |
<%= link_to 'Back', broadcasts_path %>

app/views/broadcasts/index.html.erb
<h1>Broadcasts</h1>
<%= link_to 'Channels', channels_path %>
<table>
  <tr>
    <th>Channel</th>
    <th>Broadcaster broadcast</th>
    <th>Start</th>
    <th>End</th>
    <th>Broadcaster program id</th>
    <th>Synopsis</th>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Broadcast tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @broadcasts.each do |broadcast| %>
  <tr>
    <td><%= broadcast.channel_id %></td>
    <td><%= broadcast.broadcaster_broadcast_id %></td>
    <td><%= broadcast.start %></td>
    <td><%= broadcast.end %></td>
    <td><%= broadcast.broadcaster_program_id %></td>
    <td><%= broadcast.synopsis %></td>
    <td><%= broadcast.title %></td>
    <td><%= broadcast.subtitle %></td>
    <td><%= broadcast.broadcast_list %></td>
    <td><%= link_to 'Show', broadcast %></td>
    <td><%= link_to 'Edit', edit_broadcast_path(broadcast) %></td>
    <td><%= link_to 'Destroy', broadcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Broadcast', new_broadcast_path %>

app/views/broadcasts/new.html.erb
<h1>New broadcast</h1>

<%= render 'form' %>

<%= link_to 'Back', broadcasts_path %>

app/views/broadcasts/now.html.erb
<h1>Listing broadcasts on now</h1>

<table>
  <tr>
    <th>Channel</th>
    <th>uuid</th>
    <th>Broadcaster broadcast</th>
    <th>Start</th>
    <th>End</th>
    <th>Broadcaster program uuid</th>
    <th>Synopsis</th>
    <th>Title</th>
    <th>Subtitle</th>
  </tr>

<% @broadcasts.each do |broadcast| %>
  <tr>
    <td><%= broadcast.channel_id %></td>
    <td><%= broadcast.uuid %></td>
    <td><%= broadcast.broadcaster_broadcast_id %></td>
    <td><%= broadcast.start %></td>
    <td><%= broadcast.end %></td>
    <td><%= broadcast.broadcaster_program_id %></td>
    <td><%= broadcast.synopsis %></td>
    <td><%= link_to broadcast.title, broadcast %></td>
    <td><%= broadcast.subtitle %></td>
  </tr>
<% end %>
</table>

<br />

app/views/broadcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Channel:</b>
  <%= @broadcast.channel_id %>
</p>

<p>
  <b>UUID:</b>
  <%= @broadcast.uuid %>
</p>

<p>
  <b>Broadcaster broadcast:</b>
  <%= @broadcast.broadcaster_broadcast_id %>
</p>

<p>
  <b>Start:</b>
  <%= @broadcast.start %>
</p>

<p>
  <b>End:</b>
  <%= @broadcast.end %>
</p>

<p>
  <b>Broadcaster program uuid:</b>
  <%= @broadcast.broadcaster_program_id %>
</p>

<p>
  <b>Synopsis:</b>
  <%= @broadcast.synopsis %>
</p>

<p>
  <b>Title:</b>
  <%= @broadcast.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @broadcast.subtitle %>
</p>

<p>
  <b>Broadcast tags:</b>
  <%= @broadcast.broadcast_list %>
</p>


<%= link_to 'Edit', edit_broadcast_path(@broadcast) %> |
<%= link_to 'Back', broadcasts_path %>