config/routes.rb
SecondScreen::Application.routes.draw do
  resources :statuses

  resources :users

  resources :broadcasts do
    collection do
      get 'now'
    end
    resources :statuses
  end

  resources :channels do
    member do
      post 'ingest'
    end
  end

  resources :broadcasters do
    resources :channels
  end
  
  resources :channels do
    resources :broadcasts
  end

end

app/models/broadcaster.rb
class Broadcaster < ActiveRecord::Base
  attr_accessible :logo_url, :name
  has_many :channels
  
  def as_json(options={})
    { :id => id,
      :logo_url => logo_url,
      :name => name}
  end
  
end

app/controllers/broadcasters_controller.rb
class BroadcastersController < ApplicationController
  # GET /broadcasters
  # GET /broadcasters.json
  def index
    @broadcasters = Broadcaster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @broadcasters }
    end
  end

  # GET /broadcasters/1
  # GET /broadcasters/1.json
  def show
    @broadcaster = Broadcaster.find(params[:id])
    @channels = @broadcaster.channels

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @broadcaster }
    end
  end

  # GET /broadcasters/new
  # GET /broadcasters/new.json
  def new
    @broadcaster = Broadcaster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @broadcaster }
    end
  end

  # GET /broadcasters/1/edit
  def edit
    @broadcaster = Broadcaster.find(params[:id])
  end

  # POST /broadcasters
  # POST /broadcasters.json
  def create
    @broadcaster = Broadcaster.new(params[:broadcaster])

    respond_to do |format|
      if @broadcaster.save
        format.html { redirect_to @broadcaster, notice: 'Broadcaster was successfully created.' }
        format.json { render json: @broadcaster, status: :created, location: @broadcaster }
      else
        format.html { render action: "new" }
        format.json { render json: @broadcaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /broadcasters/1
  # PUT /broadcasters/1.json
  def update
    @broadcaster = Broadcaster.find(params[:id])

    respond_to do |format|
      if @broadcaster.update_attributes(params[:broadcaster])
        format.html { redirect_to @broadcaster, notice: 'Broadcaster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @broadcaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /broadcasters/1
  # DELETE /broadcasters/1.json
  def destroy
    @broadcaster = Broadcaster.find(params[:id])
    @broadcaster.destroy

    respond_to do |format|
      format.html { redirect_to broadcasters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/broadcasters_helper.rb
module BroadcastersHelper
end

app/views/broadcasters/_form.html.erb
<%= form_for(@broadcaster) do |f| %>
  <% if @broadcaster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@broadcaster.errors.count, "error") %> prohibited this broadcaster from being saved:</h2>

      <ul>
      <% @broadcaster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br />
    <%= f.text_field :logo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/broadcasters/edit.html.erb
<h1>Editing broadcaster</h1>

<%= render 'form' %>

<%= link_to 'Show', @broadcaster %> |
<%= link_to 'Back', broadcasters_path %>

app/views/broadcasters/index.html.erb
<h1>Listing broadcasters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Logo url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @broadcasters.each do |broadcaster| %>
  <tr>
    <td><%= link_to broadcaster.name, broadcaster %></td>
    <td><%= link_to 'New Channel', new_broadcaster_channel_path(broadcaster) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Broadcaster', new_broadcaster_path %>

app/views/broadcasters/new.html.erb
<h1>New broadcaster</h1>

<%= render 'form' %>

<%= link_to 'Back', broadcasters_path %>

app/views/broadcasters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @broadcaster.name %>
</p>

<p>
  <b>Logo url:</b>
  <%= @broadcaster.logo_url %>
</p>


<table>
  <tr>
    <th>Name</th>
    <th>Logo url</th>
    <th>Ingestion url</th>
    <th>Ingestion module</th>
    <th></th>
  </tr>
<% @channels.each do |channel| %>
	<tr> 
		<td> <%= link_to channel.name, channel %> </td>
		<td> <%= image_tag channel.logo.url(:large) %></td>
		<td> <%= channel.ingestion_url %></td>
		<td> <%= channel.ingestion_module %></td>
		<td> <%= form_tag(:controller => :channels, :id => channel.id, :action => :ingest, :method => :post) do |f| %>
			  	<div class="field">
			    	<%= label_tag :date %>
			    	<%= text_field_tag :date %>
  				</div>
  				<div class="actions">
    				<%= submit_tag %>
  				</div>
  			<% end %>
		</td>
		<td> <%= link_to 'Edit', edit_channel_path(channel)%></td>
	</tr>
<% end %>
</table>

<p>
	<%= link_to 'New Channel', new_broadcaster_channel_path(@broadcaster) %>
	<%= link_to 'Edit Broadcaster', edit_broadcaster_path(@broadcaster) %> |
	<%= link_to 'Back', broadcasters_path %>
</p>